# Generated by Django 5.0.2 on 2024-03-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maincode', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='tododata',
        ),
    ]
